# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Fix project python version
default_language_version:
    python: python3.9

repos:

# general pre-commit hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
    -   id: check-added-large-files
        args: ["--maxkb=5120"]  # max 5MB

# black - code formatter
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        name: black

# isort - sort imports
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort
        args: ["--profile=black", "--filter-files"]

# flake8 - python linter
# arguments are in `setup.cfg`!
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

# pyupgrade - upgrade syntax to version 3.9
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
    -   id: pyupgrade
        args: ["--py39-plus"]
